version: '3'
services:
  app:
    restart: always
    build: .
    ports:
      - 2000:2000
    environment:
      - PGHOST=postgres
      - PGUSER=postgres
      - PGDATABASE=postgres
      - START_ID=1
      - END_ID=1002
      - NUMBER_OF_CHUNKS=10
    links:
      - postgres
  postgres:
    image: postgres
    ports:
      - 5432:5432
